# Generated by Django 5.0.6 on 2024-06-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('storyline', models.CharField(max_length=200)),
                ('duration', models.DurationField()),
                ('IMDB_rating', models.IntegerField()),
                ('cast', models.CharField(max_length=100)),
                ('starring', models.CharField(max_length=100)),
                ('available_on', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
