# Generated by Django 5.0.6 on 2024-07-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_user_remove_movies_email_remove_movies_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
